### PR TITLE
Fixes #158

### LINKED ISSUE #158: Wrong offset reported
```golang
handleMessages := func(consumerContext stream.ConsumerContext, message *amqp.Message) {
		fmt.Println("message offset:", consumerContext.Consumer.GetOffset(), ",body:", string(message.GetData()))
		consumerContext.Consumer.StoreOffset()
	}
```

the value: `consumerContext.Consumer.GetOffset()` is not correct the problem is in:

```golang 
type Consumer struct {
	currentOffset int64
```

it always starts from `0` but it _must_ use the offset coming from the delivery

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>

The  PR fixes the wrong offset stored.
It is in draft since tests are missing.

### CODE REVIEW

**Review by Zerpet — COMMENTED** [review]
This looks good, and I think it's non-breaking since the signature of `MessageHandler()` doesn't change. I'm going to add a test case to ensure the correctness of the fix.

**Comment by Zerpet** [comment]
Rebased main branch to resolve conflicts. I will do a refactor before marking this ready.

**Comment by Zerpet** [comment]
Marking as ready for review after adding a test case for the fix. @Gsantomaggio do you want to review the test case once CI passes?

**Comment by Gsantomaggio** [comment]
@Zerpet looks good to me! ty!

**Comment by kensou97** [comment]
Will it be released recently?

**Comment by Gsantomaggio** [comment]
@kensou97 https://github.com/rabbitmq/rabbitmq-stream-go-client/releases/tag/v1.0.1-rc.2 done

**Comment by kensou97** [comment]
Thank you, i'll have a try

**Comment by kensou97** [comment]
Can you try [this code](https://gist.github.com/kensou97/f11c996b2001249fcfe6869ec93d90fa)? The message with offset 100 is missing.

**Pull request merged**
